### ISSUE TITLE
Please add some additional help regarding Flatpak.

### ISSUE THREAD

**Issue by zayuim** [libretro/www.retroarch.com#7]
Since I'm (and I assume others) are new to Flatpak it could be helpful to have help with updating and gaining access to /media/, on the Flatpak install page.

I've figured out how to update.

`flatpak update --user`

But I haven't figured out how to access /media/. I can't access this because of something to do with Flatpak right?

**Comment by RobLoach** [comment]
This can be closed. Discus over at the issue and PR linked above.
