### ISSUE TITLE
Website not using https

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/www.retroarch.com#8]
retroarch.com does not use https like libretro.com, this is huge problem for websites that provide executable files because someone could pass off a virus as a new RetroArch version.

**Comment by RobLoach** [comment]
Related: https://retroarch.com looks like it gets the buildbot file browser.

**Comment by bparker06** [comment]
retroarch.com does support SSL but it uses the libretro.com certificate currently, so it will say the name is invalid.

If you're worried about executables though, you'd have to (at the very least) demand that we sign them... and I don't think anyone is willing to pay for code signing certificates for us.

**Comment by bparker06** [comment]
hmm, I did find a quite cheap service for open source projects though

https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-931.html

28 euro

**Comment by RobLoach** [comment]
Would [Let's Encrypt](https://letsencrypt.org/) work?

**Comment by meepingsnesroms** [comment]
I am not referring to signing executables, I just mean https is important if you distribute executables so someone cant do a mitm attack and swap a RetroArch executable for a virus when downloading from the website.

I am completely against any sort of executable signing as it is just another way for companys to scare people away from open source apps toward there app stores and control what people can run on there computers.

**Comment by RobLoach** [comment]
This is fixed :+1:
